export const GET_TOKEN_SUCCESS = "@GET_TOKEN_SUCCESS"
export const GET_TOKEN_FAILED = "@GET_TOKEN_FAILED"

export const GET_GENERATE_STATE = "@GET_GENERATE_STATE"

export const SET_LOADING = "@SET_LOADING"

export const GET_ORDER_LIST_SUCCESS = "@GET_ORDER_LIST_SUCCESS"
export const GET_ORDER_LIST_FAILED = "@GET_ORDER_LIST_FAILED"

export const GET_ITEM_LIST_SUCCESS = "@GET_ITEM_LIST_SUCCESS"
export const CLEAR_ITEM_LIST = "@CLEAR_ITEM_LIST"
export const GET_ITEM_LIST_FAILED = "@GET_ITEM_LIST_FAILED"

export const DELETE_ITEM_LIST_SUCCESS = "@DELETE_ITEM_LIST_SUCCESS"
export const DELETE_ITEM_LIST_FAILED = "@DELETE_ITEM_LIST_FAILED"

export const ADD_ITEM_LIST_SUCCESS = "@ADD_ITEM_LIST_SUCCESS"
export const ADD_ITEM_LIST_FAILED = "@ADD_ITEM_LIST_FAILED"

export const UPDATE_ITEM_LIST_SUCCESS = "@UPDATE_ITEM_LIST_SUCCESS"
export const UPDATE_ITEM_LIST_FAILED = "@UPDATE_ITEM_LIST_FAILED"